config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :wikis do
    resources :collaborators
  end

  resources :users, only: [:show]

  resources :charges, only: [:new, :create]

  get 'downgrade' => 'users#downgrade'

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'
end

app/models/collaborator.rb
# == Schema Information
#
# Table name: collaborators
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  wiki_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki

  accepts_nested_attributes_for :user

  validates_uniqueness_of :user, scope: :wiki
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role                   :integer
#

class User < ActiveRecord::Base
  has_many :wikis
  has_many :collaborators
  has_many :wikis, through: :collaborators
  after_initialize :init

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:standard, :premium, :admin]

  def init
    self.role   ||= :standard
  end
end

app/models/wiki.rb
# == Schema Information
#
# Table name: wikis
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  private    :boolean
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.email}",
      amount: Amount.default
    }
  end

  def create
    customer = Stripe::Customer.create(
    email: current_user.email,
    card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
    customer: customer.id,
    amount: Amount.default,
    description: "BigMoney Membership - #{current_user.email}",
    currency: 'usd'
    )

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    current_user.premium!
    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  class Amount
    class << self
      def default
        15_00
      end
    end
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def index
  end

  def about
  end

  def create
    #retrieve the wiki
    @wiki = Wiki.find(params[:wiki_id])
    #collaborators object for if the function errors out
    @collaborators = @wiki.collaborators
    #retrieve th3e user associated with the email
    @user = User.find_by(email: params[:user][:email])
    #create a new collaborator, we do it here also in case if it errors out
    @collaborator = Collaborator.new(wiki: @wiki)
    #see if user exists according to email
    if @user
      # attach user to collaborator, we do this separately again because if function errors out we want to have a collaborators object
      @collaborator.user = @user
      authorize @collaborator
      if @collaborator.save
        flash[:notice] = "Wiki was saved."
        redirect_to @wiki
      else
        # raise
        flash.now[:alert] = "There was an error saving the wiki. Please try again."
        render "wikis/edit"
      end
    else
      flash.now[:alert] = "No user associated w/ the email entered.."
      render "wikis/edit"
    end

  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render "wikis/show"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def downgrade
    @user = current_user
    @user.standard!
    @user.wikis.each do |wiki|
      wiki.update_attributes!(private: false)
    end

    flash[:notice] = "Your account has been changed to the Free Plan."
    redirect_to user_path(current_user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  # before_action :authenticate_user!, except: [:index, :show]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])

    if !policy(@wiki).show?
      flash[:alert] = "You must be a premium member to view this."
      redirect_to root_path
    end

  end

  def new
    @wiki = Wiki.new
    if !policy(@wiki).new?
      flash[:notice] = "You need at least a free account to create a Wiki. Sign up or Log in!"
      redirect_to root_path
    end
  end

  def create
    @wiki = Wiki.new
    @wiki.user = current_user
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])

    @collaborators = @wiki.collaborators
    @collaborator = Collaborator.new
    # raise
    @users = User.all

    if !policy(@wiki).edit?
      flash[:notice] = "You must be logged in to edit a Wiki."
      redirect_to @wiki
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    if current_user.admin? || current_user.premium?
      @wiki.private = params[:wiki][:private]
    end
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    render_options = {
      filter_html: true,
      hard_wrap: true,
    }
    renderer = Redcarpet::Render::HTML.new(render_options)

    extensions = {
      autolink: true,
      fenced_code_blocks: true,
      lax_spacing: true,
      no_intra_emphasis: true,
      strikethrough: true,
      superscript: true,
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= welcome_index_path %>"><font color= #0988B3>Blocipedia</font></a>
      </div>
      <div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", welcome_index_path %></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="<%= wikis_path %>">Wikis<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Wikis", wikis_path %></li>
              <li><%= link_to "New Wiki", new_wiki_path %></li>
            </ul>
          <li><%= link_to "About", welcome_about_path %></li>
        </ul>
        <div class="nav navbar-nav navbar-right">
          <div class="user_block">
          <% if user_signed_in? %>
            Signed in as: <a href="<%= user_path(current_user) %>"><strong><%= current_user.email %></strong></a> |
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
            <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
            <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </nav>
  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<p>I am a <%= current_user.role %> plan user!</p>
<br>
<% if current_user == @user %>
  <% if current_user.standard? %>
    <p>Want to take part in private wikis?</p>
    <%= link_to "Upgrade your plan", new_charge_path, class: 'btn btn-primary' %>
  <% else %>
    <p>Looking to downgrade your account to a Free user?</p>
    <%= link_to "Change to Free Plan", downgrade_path, method: :get, class: 'btn btn-primary', data: {confirm: 'All private wikis will become public if you continue.  Are you sure you would like to change to the Free plan?'} %>
  <% end %>
<% end %>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Created by: Me</p>

app/views/welcome/index.html.erb
<div id="index-title">Welcome to Blocipedia</div>

<div class="container">
  <div class="jumbotron" style="border: 2px solid grey;">
    <center><h3>Create and share Markdown Wikis</h3></center>
    <center><a type="button" class="btn btn-success btn-lg" href="<%= new_wiki_path %>">Create a new Wiki!</a></center>
  </div>

  <div class="row">
    <div class="col-sm-5">
      <h3 class="text-center">Create as many public wikis as you want!</h3>
      <p><center><%= link_to "Free Plan", new_user_registration_path, class: 'btn btn-success' %></center></p>
    </div>
    <div class="col-sm-2">
    </div>
    <div class="col-sm-5">
      <h3 class="text-center">Create private wikis!</h3>
      <% if current_user.present? && current_user.premium? %>
        <p><center><%= link_to "Create New Wiki", new_wiki_path, class: 'btn btn-success' %></center></p>
      <% elsif current_user.present? && current_user.standard? %>
        <p><center><%= link_to "Upgrade plan for Private Wikis", new_charge_path, class: 'btn btn-primary' %></center></p>
      <% else %>
        <p><center><%= link_to "Sign up and upgrade!", new_user_registration_path, class: 'btn btn-primary' %></center></p>
      <% end %>
    </div>
  </div>
</div>

app/views/wikis/_form.html.erb
<div class="row col-md-8">
  <%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki information" %>
  </div>
  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
</div>
<% end %>

app/views/wikis/edit.html.erb
<h2>Edit the Wiki.</h2>

<%= render partial: 'wikis/form', locals: { wiki: @wiki } %>

<% if !@collaborators.blank? %>
  <h4>Collaborators</h4>

  <% @collaborators.each do |c| %>
    <p>
      <%= link_to wiki_collaborator_path(@wiki, c), method: :delete do %>
        <span class="glyphicon glyphicon-remove-circle"></span>
      <%end%>
      <%= c.user.email %>
    </p>
  <%end%>
<% end %>

<%= form_for [@wiki, @collaborator] do |f| %>
 <h4><%= f.label :user_id, 'Add New Collaborators' %></h4>

 <%= fields_for :user, @collaborator.user do |ff| %>
  <%= ff.email_field(:email) %><br/><br/>
 <% end %>
 <%= f.submit class: 'btn btn-success' %>
<%end%>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h2>Looking to create a new wiki?</h2>

  <p class="bg-info">Please make sure there isn't a wiki already started on the topic.</p>

<%= render partial: 'form', locals: { wiki: @wiki } %>

app/views/wikis/show.html.erb
<h3><%= @wiki.title %></h3>
<p>This wiki is <%= @wiki.private? ? "private" : "public" %>.</p>
<hr>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown @wiki.body %></p>
  </div>
  <% if current_user.present? %>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
  <% end %>
  <br>
  <div class="col-md-3">
    <p style="font-size: 12px">Last updated on <%= @wiki.updated_at.strftime("%d %b, %Y @ %H:%M %Z") %></p>
  </div>
</div>